import type { Meta, StoryObj } from "@storybook/react-vite";

import { Table } from "./index";

const meta: Meta<typeof Table> = {
	component: Table,
	subcomponents: {
		Header: Table.Header,
		Body: Table.Body,
		Footer: Table.Footer,
		Row: Table.Row,
		Cell: Table.Cell,
		HeaderCell: Table.HeaderCell,
	},
	title: "Table",
	parameters: {
		layout: "fullscreen",
	},
};

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
	render: (args) => (
		<Table {...args}>
			<Table.Header>
				<Table.Row>
					<Table.HeaderCell>ID</Table.HeaderCell>
					<Table.HeaderCell>Name</Table.HeaderCell>
					<Table.HeaderCell>Email</Table.HeaderCell>
					<Table.HeaderCell>Age</Table.HeaderCell>
					<Table.HeaderCell>Country</Table.HeaderCell>
					<Table.HeaderCell>Job title</Table.HeaderCell>
					<Table.HeaderCell>Initials</Table.HeaderCell>
					<Table.HeaderCell>Email domain</Table.HeaderCell>
					<Table.HeaderCell>Seniority</Table.HeaderCell>
					<Table.HeaderCell>Team</Table.HeaderCell>
					<Table.HeaderCell>Status</Table.HeaderCell>
				</Table.Row>
			</Table.Header>
			<Table.Body>
				{DATA.map((user) => (
					<Table.Row interactive key={user.id}>
						<Table.Cell>{user.id}</Table.Cell>
						<Table.Cell>{user.name}</Table.Cell>
						<Table.Cell>{user.email}</Table.Cell>
						<Table.Cell>{user.age}</Table.Cell>
						<Table.Cell>{user.country}</Table.Cell>
						<Table.Cell>{user.jobTitle}</Table.Cell>
						<Table.Cell>{user.initials}</Table.Cell>
						<Table.Cell>{user.emailDomain}</Table.Cell>
						<Table.Cell>{user.seniority}</Table.Cell>
						<Table.Cell>{user.team}</Table.Cell>
						<Table.Cell>{user.isActive ? "Active" : "Inactive"}</Table.Cell>
					</Table.Row>
				))}
			</Table.Body>
		</Table>
	),
};

const DATA = [
	{
		id: 1,
		name: "John Doe",
		email: "john.doe@example.com",
		age: 28,
		country: "USA",
		jobTitle: "Software Engineer",
		initials: "JD",
		emailDomain: "example.com",
		seniority: "Junior",
		team: "Engineering",
		isActive: true,
	},
	{
		id: 2,
		name: "Jane Smith",
		email: "jane.smith@example.com",
		age: 34,
		country: "Canada",
		jobTitle: "Data Scientist",
		initials: "JS",
		emailDomain: "example.com",
		seniority: "Mid-level",
		team: "Operations",
		isActive: false,
	},
	{
		id: 3,
		name: "Michael Johnson",
		email: "michael.j@example.com",
		age: 45,
		country: "UK",
		jobTitle: "Product Manager",
		initials: "MJ",
		emailDomain: "example.com",
		seniority: "Senior",
		team: "Operations",
		isActive: true,
	},
	{
		id: 4,
		name: "Emily Davis",
		email: "emily.d@example.com",
		age: 29,
		country: "Australia",
		jobTitle: "UX Designer",
		initials: "ED",
		emailDomain: "example.com",
		seniority: "Junior",
		team: "Design",
		isActive: true,
	},
	{
		id: 5,
		name: "Robert Brown",
		email: "robert.b@example.com",
		age: 31,
		country: "Germany",
		jobTitle: "DevOps Engineer",
		initials: "RB",
		emailDomain: "example.com",
		seniority: "Mid-level",
		team: "Engineering",
		isActive: false,
	},
	{
		id: 6,
		name: "Sarah Wilson",
		email: "sarah.w@example.com",
		age: 27,
		country: "France",
		jobTitle: "Frontend Developer",
		initials: "SW",
		emailDomain: "example.com",
		seniority: "Junior",
		team: "Engineering",
		isActive: true,
	},
	{
		id: 7,
		name: "David Taylor",
		email: "david.t@example.com",
		age: 40,
		country: "USA",
		jobTitle: "CTO",
		initials: "DT",
		emailDomain: "example.com",
		seniority: "Senior",
		team: "Operations",
		isActive: true,
	},
	{
		id: 8,
		name: "Lisa Anderson",
		email: "lisa.a@example.com",
		age: 33,
		country: "Sweden",
		jobTitle: "Marketing Manager",
		initials: "LA",
		emailDomain: "example.com",
		seniority: "Mid-level",
		team: "Growth",
		isActive: false,
	},
	{
		id: 9,
		name: "James Martinez",
		email: "james.m@example.com",
		age: 26,
		country: "Spain",
		jobTitle: "Backend Developer",
		initials: "JM",
		emailDomain: "example.com",
		seniority: "Junior",
		team: "Engineering",
		isActive: true,
	},
	{
		id: 10,
		name: "Patricia Lee",
		email: "patricia.l@example.com",
		age: 38,
		country: "Japan",
		jobTitle: "HR Specialist",
		initials: "PL",
		emailDomain: "example.com",
		seniority: "Mid-level",
		team: "Operations",
		isActive: true,
	},
	{
		id: 11,
		name: "Thomas Clark",
		email: "thomas.c@example.com",
		age: 30,
		country: "USA",
		jobTitle: "QA Engineer",
		initials: "TC",
		emailDomain: "example.com",
		seniority: "Mid-level",
		team: "Engineering",
		isActive: false,
	},
	{
		id: 12,
		name: "Jennifer Rodriguez",
		email: "jennifer.r@example.com",
		age: 25,
		country: "Mexico",
		jobTitle: "Graphic Designer",
		initials: "JR",
		emailDomain: "example.com",
		seniority: "Junior",
		team: "Design",
		isActive: true,
	},
	{
		id: 13,
		name: "Daniel Lewis",
		email: "daniel.l@example.com",
		age: 42,
		country: "UK",
		jobTitle: "Financial Analyst",
		initials: "DL",
		emailDomain: "example.com",
		seniority: "Senior",
		team: "Operations",
		isActive: true,
	},
	{
		id: 14,
		name: "Nancy Walker",
		email: "nancy.w@example.com",
		age: 36,
		country: "Canada",
		jobTitle: "Project Manager",
		initials: "NW",
		emailDomain: "example.com",
		seniority: "Mid-level",
		team: "Operations",
		isActive: false,
	},
	{
		id: 15,
		name: "Charles Hall",
		email: "charles.h@example.com",
		age: 39,
		country: "Germany",
		jobTitle: "Sales Director",
		initials: "CH",
		emailDomain: "example.com",
		seniority: "Mid-level",
		team: "Growth",
		isActive: true,
	},
	{
		id: 16,
		name: "Karen Young",
		email: "karen.y@example.com",
		age: 28,
		country: "Australia",
		jobTitle: "Content Writer",
		initials: "KY",
		emailDomain: "example.com",
		seniority: "Junior",
		team: "Operations",
		isActive: true,
	},
	{
		id: 17,
		name: "Christopher Allen",
		email: "christopher.a@example.com",
		age: 35,
		country: "USA",
		jobTitle: "System Architect",
		initials: "CA",
		emailDomain: "example.com",
		seniority: "Mid-level",
		team: "Engineering",
		isActive: false,
	},
	{
		id: 18,
		name: "Amanda King",
		email: "amanda.k@example.com",
		age: 31,
		country: "France",
		jobTitle: "Business Analyst",
		initials: "AK",
		emailDomain: "example.com",
		seniority: "Mid-level",
		team: "Operations",
		isActive: true,
	},
	{
		id: 19,
		name: "Matthew Wright",
		email: "matthew.w@example.com",
		age: 44,
		country: "Sweden",
		jobTitle: "CEO",
		initials: "MW",
		emailDomain: "example.com",
		seniority: "Senior",
		team: "Operations",
		isActive: true,
	},
	{
		id: 20,
		name: "Elizabeth Scott",
		email: "elizabeth.s@example.com",
		age: 29,
		country: "Spain",
		jobTitle: "Social Media Manager",
		initials: "ES",
		emailDomain: "example.com",
		seniority: "Junior",
		team: "Operations",
		isActive: false,
	},
	{
		id: 21,
		name: "Steven Green",
		email: "steven.g@example.com",
		age: 32,
		country: "Japan",
		jobTitle: "Mobile Developer",
		initials: "SG",
		emailDomain: "example.com",
		seniority: "Mid-level",
		team: "Engineering",
		isActive: true,
	},
	{
		id: 22,
		name: "Michelle Baker",
		email: "michelle.b@example.com",
		age: 27,
		country: "USA",
		jobTitle: "UI Designer",
		initials: "MB",
		emailDomain: "example.com",
		seniority: "Junior",
		team: "Design",
		isActive: true,
	},
	{
		id: 23,
		name: "Brian Adams",
		email: "brian.a@example.com",
		age: 41,
		country: "UK",
		jobTitle: "Technical Writer",
		initials: "BA",
		emailDomain: "example.com",
		seniority: "Senior",
		team: "Operations",
		isActive: false,
	},
	{
		id: 24,
		name: "Laura Nelson",
		email: "laura.n@example.com",
		age: 30,
		country: "Canada",
		jobTitle: "Customer Support",
		initials: "LN",
		emailDomain: "example.com",
		seniority: "Mid-level",
		team: "Operations",
		isActive: true,
	},
	{
		id: 25,
		name: "Kevin Carter",
		email: "kevin.c@example.com",
		age: 37,
		country: "Germany",
		jobTitle: "Security Engineer",
		initials: "KC",
		emailDomain: "example.com",
		seniority: "Mid-level",
		team: "Engineering",
		isActive: true,
	},
	{
		id: 26,
		name: "Sophia Mitchell",
		email: "sophia.m@example.com",
		age: 26,
		country: "Australia",
		jobTitle: "Data Analyst",
		initials: "SM",
		emailDomain: "example.com",
		seniority: "Junior",
		team: "Operations",
		isActive: false,
	},
	{
		id: 27,
		name: "Jason Roberts",
		email: "jason.r@example.com",
		age: 43,
		country: "USA",
		jobTitle: "Cloud Engineer",
		initials: "JR",
		emailDomain: "example.com",
		seniority: "Senior",
		team: "Engineering",
		isActive: true,
	},
	{
		id: 28,
		name: "Olivia Turner",
		email: "olivia.t@example.com",
		age: 34,
		country: "France",
		jobTitle: "Product Designer",
		initials: "OT",
		emailDomain: "example.com",
		seniority: "Mid-level",
		team: "Design",
		isActive: true,
	},
	{
		id: 29,
		name: "Gary Phillips",
		email: "gary.p@example.com",
		age: 38,
		country: "Sweden",
		jobTitle: "Network Engineer",
		initials: "GP",
		emailDomain: "example.com",
		seniority: "Mid-level",
		team: "Engineering",
		isActive: false,
	},
	{
		id: 30,
		name: "Emma Campbell",
		email: "emma.c@example.com",
		age: 29,
		country: "Spain",
		jobTitle: "SEO Specialist",
		initials: "EC",
		emailDomain: "example.com",
		seniority: "Junior",
		team: "Growth",
		isActive: true,
	},
	{
		id: 31,
		name: "Frank Parker",
		email: "frank.p@example.com",
		age: 40,
		country: "Japan",
		jobTitle: "Database Administrator",
		initials: "FP",
		emailDomain: "example.com",
		seniority: "Senior",
		team: "Operations",
		isActive: true,
	},
	{
		id: 32,
		name: "Grace Evans",
		email: "grace.e@example.com",
		age: 33,
		country: "USA",
		jobTitle: "HR Manager",
		initials: "GE",
		emailDomain: "example.com",
		seniority: "Mid-level",
		team: "Operations",
		isActive: false,
	},
	{
		id: 33,
		name: "Henry Edwards",
		email: "henry.e@example.com",
		age: 36,
		country: "UK",
		jobTitle: "Business Development",
		initials: "HE",
		emailDomain: "example.com",
		seniority: "Mid-level",
		team: "Operations",
		isActive: true,
	},
	{
		id: 34,
		name: "Chloe Collins",
		email: "chloe.c@example.com",
		age: 28,
		country: "Canada",
		jobTitle: "Frontend Developer",
		initials: "CC",
		emailDomain: "example.com",
		seniority: "Junior",
		team: "Engineering",
		isActive: true,
	},
	{
		id: 35,
		name: "George Stewart",
		email: "george.s@example.com",
		age: 45,
		country: "Germany",
		jobTitle: "CTO",
		initials: "GS",
		emailDomain: "example.com",
		seniority: "Senior",
		team: "Operations",
		isActive: false,
	},
	{
		id: 36,
		name: "Isabella Sanchez",
		email: "isabella.s@example.com",
		age: 31,
		country: "Australia",
		jobTitle: "Marketing Specialist",
		initials: "IS",
		emailDomain: "example.com",
		seniority: "Mid-level",
		team: "Growth",
		isActive: true,
	},
	{
		id: 37,
		name: "Samuel Morris",
		email: "samuel.m@example.com",
		age: 39,
		country: "USA",
		jobTitle: "DevOps Engineer",
		initials: "SM",
		emailDomain: "example.com",
		seniority: "Mid-level",
		team: "Engineering",
		isActive: true,
	},
	{
		id: 38,
		name: "Mia Reed",
		email: "mia.r@example.com",
		age: 27,
		country: "France",
		jobTitle: "UX Researcher",
		initials: "MR",
		emailDomain: "example.com",
		seniority: "Junior",
		team: "Design",
		isActive: false,
	},
	{
		id: 39,
		name: "Daniel Cook",
		email: "daniel.c@example.com",
		age: 42,
		country: "Sweden",
		jobTitle: "Financial Controller",
		initials: "DC",
		emailDomain: "example.com",
		seniority: "Senior",
		team: "Operations",
		isActive: true,
	},
	{
		id: 40,
		name: "Charlotte Morgan",
		email: "charlotte.m@example.com",
		age: 30,
		country: "Spain",
		jobTitle: "Graphic Designer",
		initials: "CM",
		emailDomain: "example.com",
		seniority: "Mid-level",
		team: "Design",
		isActive: true,
	},
	{
		id: 41,
		name: "Anthony Bell",
		email: "anthony.b@example.com",
		age: 35,
		country: "Japan",
		jobTitle: "Software Engineer",
		initials: "AB",
		emailDomain: "example.com",
		seniority: "Mid-level",
		team: "Engineering",
		isActive: false,
	},
	{
		id: 42,
		name: "Amelia Murphy",
		email: "amelia.m@example.com",
		age: 29,
		country: "USA",
		jobTitle: "Product Manager",
		initials: "AM",
		emailDomain: "example.com",
		seniority: "Junior",
		team: "Operations",
		isActive: true,
	},
	{
		id: 43,
		name: "Liam Bailey",
		email: "liam.b@example.com",
		age: 41,
		country: "UK",
		jobTitle: "QA Engineer",
		initials: "LB",
		emailDomain: "example.com",
		seniority: "Senior",
		team: "Engineering",
		isActive: true,
	},
	{
		id: 44,
		name: "Harper Rivera",
		email: "harper.r@example.com",
		age: 33,
		country: "Canada",
		jobTitle: "Data Scientist",
		initials: "HR",
		emailDomain: "example.com",
		seniority: "Mid-level",
		team: "Operations",
		isActive: false,
	},
	{
		id: 45,
		name: "Sebastian Cooper",
		email: "sebastian.c@example.com",
		age: 37,
		country: "Germany",
		jobTitle: "Sales Manager",
		initials: "SC",
		emailDomain: "example.com",
		seniority: "Mid-level",
		team: "Growth",
		isActive: true,
	},
	{
		id: 46,
		name: "Evelyn Richardson",
		email: "evelyn.r@example.com",
		age: 28,
		country: "Australia",
		jobTitle: "Content Writer",
		initials: "ER",
		emailDomain: "example.com",
		seniority: "Junior",
		team: "Operations",
		isActive: true,
	},
	{
		id: 47,
		name: "Jack Cox",
		email: "jack.c@example.com",
		age: 44,
		country: "USA",
		jobTitle: "System Architect",
		initials: "JC",
		emailDomain: "example.com",
		seniority: "Senior",
		team: "Engineering",
		isActive: false,
	},
	{
		id: 48,
		name: "Abigail Ward",
		email: "abigail.w@example.com",
		age: 32,
		country: "France",
		jobTitle: "Business Analyst",
		initials: "AW",
		emailDomain: "example.com",
		seniority: "Mid-level",
		team: "Operations",
		isActive: true,
	},
	{
		id: 49,
		name: "Benjamin Simmons",
		email: "benjamin.s@example.com",
		age: 38,
		country: "Sweden",
		jobTitle: "Mobile Developer",
		initials: "BS",
		emailDomain: "example.com",
		seniority: "Mid-level",
		team: "Engineering",
		isActive: true,
	},
	{
		id: 50,
		name: "Scarlett Foster",
		email: "scarlett.f@example.com",
		age: 30,
		country: "Spain",
		jobTitle: "UI Designer",
		initials: "SF",
		emailDomain: "example.com",
		seniority: "Mid-level",
		team: "Design",
		isActive: false,
	},
	{
		id: 51,
		name: "Lucas Simmons",
		email: "lucas.s@example.com",
		age: 43,
		country: "Japan",
		jobTitle: "Cloud Engineer",
		initials: "LS",
		emailDomain: "example.com",
		seniority: "Senior",
		team: "Engineering",
		isActive: true,
	},
	{
		id: 52,
		name: "Hannah Butler",
		email: "hannah.b@example.com",
		age: 27,
		country: "USA",
		jobTitle: "HR Specialist",
		initials: "HB",
		emailDomain: "example.com",
		seniority: "Junior",
		team: "Operations",
		isActive: true,
	},
	{
		id: 53,
		name: "Nathan Scott",
		email: "nathan.s@example.com",
		age: 36,
		country: "UK",
		jobTitle: "Technical Writer",
		initials: "NS",
		emailDomain: "example.com",
		seniority: "Mid-level",
		team: "Operations",
		isActive: false,
	},
	{
		id: 54,
		name: "Zoey Adams",
		email: "zoey.a@example.com",
		age: 31,
		country: "Canada",
		jobTitle: "Customer Support",
		initials: "ZA",
		emailDomain: "example.com",
		seniority: "Mid-level",
		team: "Operations",
		isActive: true,
	},
	{
		id: 55,
		name: "Dylan Baker",
		email: "dylan.b@example.com",
		age: 40,
		country: "Germany",
		jobTitle: "Security Engineer",
		initials: "DB",
		emailDomain: "example.com",
		seniority: "Senior",
		team: "Engineering",
		isActive: true,
	},
];
