/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as privateLayoutRouteImport } from './routes/(private)/layout'
import { Route as guestauthLayoutRouteImport } from './routes/(guest)/(auth)/layout'
import { Route as privatehomePageRouteImport } from './routes/(private)/(home)/page'
import { Route as guestauthLoginPageRouteImport } from './routes/(guest)/(auth)/login/page'
import { Route as guestauthForgotPasswordPageRouteImport } from './routes/(guest)/(auth)/forgot-password/page'

const privateLayoutRoute = privateLayoutRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const guestauthLayoutRoute = guestauthLayoutRouteImport.update({
  id: '/(guest)/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const privatehomePageRoute = privatehomePageRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => privateLayoutRoute,
} as any)
const guestauthLoginPageRoute = guestauthLoginPageRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => guestauthLayoutRoute,
} as any)
const guestauthForgotPasswordPageRoute =
  guestauthForgotPasswordPageRouteImport.update({
    id: '/forgot-password/',
    path: '/forgot-password/',
    getParentRoute: () => guestauthLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof privatehomePageRoute
  '/forgot-password/': typeof guestauthForgotPasswordPageRoute
  '/login/': typeof guestauthLoginPageRoute
}
export interface FileRoutesByTo {
  '/': typeof privatehomePageRoute
  '/forgot-password': typeof guestauthForgotPasswordPageRoute
  '/login': typeof guestauthLoginPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(private)': typeof privateLayoutRouteWithChildren
  '/(guest)/(auth)': typeof guestauthLayoutRouteWithChildren
  '/(private)/(home)/': typeof privatehomePageRoute
  '/(guest)/(auth)/forgot-password/': typeof guestauthForgotPasswordPageRoute
  '/(guest)/(auth)/login/': typeof guestauthLoginPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/forgot-password/' | '/login/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/forgot-password' | '/login'
  id:
    | '__root__'
    | '/(private)'
    | '/(guest)/(auth)'
    | '/(private)/(home)/'
    | '/(guest)/(auth)/forgot-password/'
    | '/(guest)/(auth)/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  privateLayoutRoute: typeof privateLayoutRouteWithChildren
  guestauthLayoutRoute: typeof guestauthLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(guest)/(auth)': {
      id: '/(guest)/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof guestauthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/(home)/': {
      id: '/(private)/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof privatehomePageRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(guest)/(auth)/login/': {
      id: '/(guest)/(auth)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof guestauthLoginPageRouteImport
      parentRoute: typeof guestauthLayoutRoute
    }
    '/(guest)/(auth)/forgot-password/': {
      id: '/(guest)/(auth)/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof guestauthForgotPasswordPageRouteImport
      parentRoute: typeof guestauthLayoutRoute
    }
  }
}

interface privateLayoutRouteChildren {
  privatehomePageRoute: typeof privatehomePageRoute
}

const privateLayoutRouteChildren: privateLayoutRouteChildren = {
  privatehomePageRoute: privatehomePageRoute,
}

const privateLayoutRouteWithChildren = privateLayoutRoute._addFileChildren(
  privateLayoutRouteChildren,
)

interface guestauthLayoutRouteChildren {
  guestauthForgotPasswordPageRoute: typeof guestauthForgotPasswordPageRoute
  guestauthLoginPageRoute: typeof guestauthLoginPageRoute
}

const guestauthLayoutRouteChildren: guestauthLayoutRouteChildren = {
  guestauthForgotPasswordPageRoute: guestauthForgotPasswordPageRoute,
  guestauthLoginPageRoute: guestauthLoginPageRoute,
}

const guestauthLayoutRouteWithChildren = guestauthLayoutRoute._addFileChildren(
  guestauthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  privateLayoutRoute: privateLayoutRouteWithChildren,
  guestauthLayoutRoute: guestauthLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
