/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  features: {
    userManagement: {
      authentication: {
        LoginWithCredentials: () => import('#src/features/user_management/authentication/controllers/login_with_credentials.controller'),
        Logout: () => import('#src/features/user_management/authentication/controllers/logout.controller'),
      },
      profile: {
        View: () => import('#src/features/user_management/profile/controllers/view.controller'),
      },
    },
  },
}
