/**
* This file is automatically generated.
* DO NOT EDIT manually
*/
/// <reference path="./manifest.d.ts" />

export type Pagination = ReturnType<typeof import("#presenters/pagination.presenter").default.prototype.toJSON>;

export type User = ReturnType<typeof import("#presenters/user.presenter").default.prototype.toJSON>;
