import { hooks } from "@adonisjs/core/app";

export default hooks.init((_parent, _hooksManager, indexGenerator) => {
	indexGenerator.add("dataType", {
		source: "./src/presenters",
		as: (files, writer) => {
			writer
				.write("/**")
				.write("* This file is automatically generated.")
				.write("* DO NOT EDIT manually")
				.write("*/")
				.writeLine('/// <reference path="./manifest.d.ts" />');

			for (const [file] of Object.entries(files.asList())) {
				const variableName =
					file.split("/").pop()!.split(".")[0].slice(0, 1).toUpperCase() +
					file
						.split("/")
						.pop()!
						.split(".")[0]
						.replace(/[-_](.)/g, (_, char) => char.toUpperCase())
						.slice(1);
				const importPath = `#presenters/${file}`;

				writer.writeLine(
					`export type ${variableName} = Awaited<ReturnType<typeof import("${importPath}").default.prototype.toJSON>>;`,
				);
			}

			return writer.toString();
		},
		output: "./.adonisjs/client/data.d.ts",
	});
});
